DEBUG=Debug
RELEASE=Release
RELWITHDEBUGINFO=RelWithDebInfo
MINSIZEREL=MinSizeRel

BUILD_TYPE="-DCMAKE_BUILD_TYPE="
echo $BUILD_TYPE

if [ "$1" = "r" ]; then
	BUILD_TYPE="$BUILD_TYPE$RELEASE"
	mkdir $RELEASE; cd $RELEASE;
elif ["$1" = "d" ]; then
	BUILD_TYPE="$BUILD_TYPE$DEBUG"
	mkdir $DEBUG; cd $DEBUG;
elif ["$1" = "rd" ]; then
	BUILD_TYPE="$BUILD_TYPE$RELWITHDEBUGINFO"
	mkdir $RELWITHDEBUGINFO; cd $RELWITHDEBUGINFO;
elif ["$1" = "mr" ]; then
	BUILD_TYPE="$BUILD_TYPE$MINSIZEREL"
	mkdir $MINSIZEREL; cd $MINSIZEREL;
fi
CMAKE_BUILD_CMD_PROJ="cmake -j 4 $BUILD_TYPE .."
eval $CMAKE_BUILD_CMD_PROJ
echo "Command used: $CMAKE_BUILD_CMD_PROJ"
cd ..
